### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by ignjat** [sorccu/node-jpeg-turbo#2]
Trying to run on Ubuntu 14.04lts I get this error:
Cannot find module '~/node_modules/jpeg-turbo/lib/binding/node-v47-linux-x64/jpegturbo.node
I see that this exists:
jpeg-turbo/lib/binding/node-v46-linux-x64/jpegturbo.node

Any clues?

**Comment by sorccu** [comment]
Did you update nodejs after installing jpeg-turbo?

**Comment by ignjat** [comment]
It was on 4.4.0. After updating to 5.1.x this went away. Thanks.
